services:
  fpm:
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./logs:/var/www/mail.gnuweeb.org/logs
      - ./storage:/var/www/mail.gnuweeb.org/storage
  mysql:
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - .env
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql:ro

version: "2"